POST http://localhost:5555/v1/users
Content-Type : application/json

{
      "first_name": "testttt",
      "last_name": "çamarcheeee",
      "street_name": "Bghffghfghfghfgh",
      "street_number": 14,
      "town": "balecontest",
      "postcode": "59500",
      "department": "Paris",
      "country": "RIOT",
      "email": "mendozddfsdfpasddtrick@emtrac.com",
      "password": "sdfsdfsdfsdf14564ZESDF",
      "nickname": "Bowmfdfdeux",
      "profile_picture": "http://seeding/osef"
}

###

PATCH http://localhost:5555/v1/users/user/2
Content-Type: application/json

{
      "first_name": "YASUOOOOOOOO",
      "last_name": "okkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk"
}

###
DELETE http://localhost:5555/v1/users/user/1
Content-Type: application/json

### 

GET http://localhost:5555/v1/users

----------------------------------------------------- Family 

###

POST http://localhost:5555/v1/families
Content-Type: application/json

{
      "name": "testFamille!!",
      "picture": "çamarcheeee",
      "description": "coucou"
}

###

PATCH http://localhost:5555/v1/families/family/6
Content-Type: application/json

{
      "name": "coucoujeviensdechanger !!"
}

###

DELETE http://localhost:5555/v1/families/family/6
Content-Type: application/json

--------------------------------------------------------- Variety

###
POST http://localhost:5555/v1/varieties
Content-Type: application/json

{
      "name": "YASUOOOOOO",
      "picture": "YONEEEEEEE",
      "description": "HARDCARYYYYYY",
      "family_id": 1
}

###

PATCH http://localhost:5555/v1/varieties/variety/6
Content-Type: application/json

{     
      "name" : "JE CHANGEEE MDRRRR"
}


###

DELETE http://localhost:5555/v1/varieties/variety/6

------------------------------------------------------------ Operations

###

POST http://localhost:5555/v1/operations
Content-Type: application/json

{
      "date" : "2020-04-11",
      "quantity" : 15.5,
      "product_name" : "DEVELOPPEURTESTTTTTT",
      "maker" : "testttttMaker",
      "operation_type_id" : 2,
      "board_id" : 3
}

###

PATCH http://localhost:5555/v1/operations/operation/7
Content-Type: application/json

{
      "quantity" : 16.5,
      "date" : "2020-04-04",
      "maker" : "Yasuoooooooooooo"
}

###

DELETE http://localhost:5555/v1/operations/operation/7